### ISSUE TITLE
dataset.json missing

### ISSUE THREAD

**Issue by tischi** [mobie/zebrafish-lm-datasets#1]
Hi @constantinpape,

The dataset.json seems missing everywhere.

**Comment by constantinpape** [comment]
No, it's there, e.g. https://github.com/mobie/zebrafish-lm-datasets/blob/spec-v2/data/membrane/dataset.json
Make sure that you are looking on the right branch (`spec-v2`) instead of `main`.

**Comment by tischi** [comment]
Good point!

There's a parsing error in the `/membrane/dataset.json` though:

```
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie2.serialize.DatasetJsonParser.getDataset(DatasetJsonParser.java:18)
	at de.embl.cba.mobie2.MoBIE2.<init>(MoBIE2.java:68)
	at projects.OpenRemoteZebrafish.main(OpenRemoteZebrafish.java:15)
```

Not sure yet what it is, maybe just some bracket or comma?


One question: Why do we have a `tableDataLocation` in the `sourceTransforms`?

```
    "small-grid-view": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              0.0,
              255.0
            ],
            "name": "membrane",
            "opacity": 1.0,
            "sources": [
              "056F63395C_lynEGFP",
              "08B96BE794_lynEGFP"
            ]
          }
        },
        {
          "segmentationDisplay": {
            "lut": "glasbey",
            "name": "membrane-segmentation",
            "opacity": 0.5,
            "sources": [
              "056F63395C_lynEGFP_seg",
              "08B96BE794_lynEGFP_seg"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "grid": {
            "sources": [
              [
                "056F63395C_lynEGFP",
                "056F63395C_lynEGFP_seg"
              ],
              [
                "08B96BE794_lynEGFP",
                "08B96BE794_lynEGFP_seg"
              ]
            ],
            "tableDataLocation": "tables/small-grid-view"
          }
        }
      ],
```

**Comment by constantinpape** [comment]
> There's a parsing error in the `/membrane/dataset.json` though:

The json is valid:
```python
import json
with open('data/membrane/dataset.json') as f:
  mdata = json.load(f)
```
works fine, and it also passes the jsonschema for datasets.
So I guess there is some mismatch between the schema and your gson loader.

> One question: Why do we have a `tableDataLocation` in the `sourceTransforms`?

Grid views have a `tableDataLocation` for the associated table, see `Grid Views` in https://mobie.github.io/specs/mobie_spec.html.

**Comment by tischi** [comment]
> Grid views have a tableDataLocation for the associated table, see Grid Views in https://mobie.github.io/specs/mobie_spec.html.

Oh, interesting, my code currently is loading the table data from all the segmentation sources and concatenating them....
Not sure what's better and whether we even should support both? Ah, I see that's image based metadata... Then it makes sense!

**Comment by tischi** [comment]
In fact, not image based but grid position based.
